# Generated by Django 2.2.1 on 2019-05-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_homework_date_posted'),
        ('events', '0002_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='course',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='lessons.Course'),
            preserve_default=False,
        ),
    ]
