# Generated by Django 2.2.1 on 2019-05-28 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
