# Generated by Django 2.2.1 on 2019-05-29 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190528_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
