# Generated by Django 2.2.1 on 2019-05-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default="None", max_length=320),
            preserve_default=False,
        ),
    ]
