# Generated by Django 2.2.1 on 2019-05-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='chapter',
            field=models.CharField(max_length=16),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
