# Generated by Django 2.2.1 on 2019-05-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20190526_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_files'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_video',
            field=models.FileField(blank=True, null=True, upload_to='lesson_vids'),
        ),
    ]
