# Generated by Django 2.2.1 on 2019-05-27 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0004_auto_20190527_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='lesson_att'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='task',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='homework_att')),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Rejected', 'Rejected'), ('Done', 'Done')], default='Not yet available', max_length=64)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson')),
            ],
        ),
    ]
