# Generated by Django 2.2.1 on 2019-05-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20190527_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('Not yet available', 'Not yet available'), ('Available', 'Available')], default='Not yet available', max_length=64),
        ),
    ]
