# Generated by Django 2.2.1 on 2019-05-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20190528_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('Not available', 'Not available'), ('Available', 'Available')], default='Not yet available', max_length=64),
        ),
    ]
