# Generated by Django 2.2.1 on 2019-05-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_auto_20190528_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Rejected', 'Rejected'), ('Done', 'Done')], default='Not available', max_length=64),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('Not available', 'Not available'), ('Available', 'Available')], default='Not available', max_length=64),
        ),
    ]
